FROM python:3.9-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install -r requirements.txt
COPY . .

# 👇 Generate gRPC code from .proto file automatically
RUN python -m grpc_tools.protoc \
    -I. \
    --python_out=. \
    --grpc_python_out=. \
    product.proto

EXPOSE 8000 50051
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]